# Generated by Django 4.2.6 on 2023-11-17 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold')], default='available', max_length=10)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('engine_type', models.CharField(max_length=50)),
                ('transmission_type', models.CharField(max_length=50)),
                ('exterior_color', models.CharField(max_length=50)),
                ('interior_color', models.CharField(max_length=50)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], default='petrol', max_length=50)),
                ('kilometer_driven', models.PositiveIntegerField()),
                ('owner', models.CharField(choices=[('first', 'First'), ('second', 'Second'), ('third', 'Third')], default='first', max_length=10)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='car_images/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='car_images/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='car_images/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='car_images/')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='car_images/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
    ]
