# Generated by Django 4.2.6 on 2024-02-18 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessory_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('audio', 'Audio'), ('body_parts', 'Body Parts'), ('exterior', 'Exterior'), ('interior', 'Interior')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('warranty', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
