# Generated by Django 4.2.6 on 2024-04-02 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='accessory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.accessory'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_datetime',
            field=models.DateTimeField(default='2024-04-04T00:00:00Z'),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
